In [10]:
import numpy as np
import pygame

# Initialize Pygame
pygame.init()
frame = np.load('rest.np.npy')
print("Frame shape:", frame.shape)
# Example frame of 0s and 1s
# frame = np.array([
#     [0, 1, 0, 1],
#     [1, 0, 1, 0],
#     [0, 1, 0, 1],
#     [1, 0, 1, 0]
# ])
print(frame[0])
# Set screen dimensions and scaling
width, height = frame.shape
scale = 10
screen_width, screen_height = width * scale, height * scale

# Create Pygame screen
screen = pygame.display.set_mode((screen_width, screen_height))

# Convert the frame to an RGB surface
frame_surface = (frame[:, :, np.newaxis] ).repeat(3, axis=2).astype(np.uint8)
print("Frame surface shape:", frame_surface.shape)
print("Frame surface data:\n", frame_surface)

# Make a Pygame surface from the array
surface = pygame.surfarray.make_surface(frame_surface)
print("Surface created:", surface)

# Scale the surface
scaled_surface = pygame.transform.scale(surface, (screen_width, screen_height))
print("Scaled surface created:", scaled_surface)

# Blit to the screen and update display
screen.blit(scaled_surface, (0, 0))
pygame.display.flip()

# Print the frame for debugging
print('\n'.join([''.join(['#' if pixel else '.' for pixel in row]) for row in frame]))

# Keep the window open for a short duration to view the output
pygame.time.wait(2000)

# Quit Pygame
pygame.quit()


Frame shape: (32, 64)
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0 255   0   0   0   0   0   0   0   0   0
   0 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]
Frame surface shape: (32, 64, 3)
Frame surface data:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Surface created: <Surface(32x64x32 SW)>
Scaled surface created: <Surface(320x640x32 SW)>
..........................#..........#..........................
..........................#..........#..........................
..........................#...

In [1]:
from experiment_tracking.Logger import Logger
from fastapi.responses import JSONResponse
logger = Logger()
print(JSONResponse(logger.get_experiment_list()))

In [7]:
logger.experiment_name

'20240715-002750'

In [8]:
logger.experiment_name = '20240715-002750'
logger.get_saved_metrics()

experiments/20240715-002750


{'batch_loss': [[0, 0.03936917334794998],
  [0, 0.030052365735173225],
  [0, 0.021686341613531113],
  [0, 0.014445390552282333],
  [0, 0.009441970847547054],
  [0, 0.006507685407996178],
  [0, 0.006296673323959112],
  [0, 0.007983316667377949],
  [0, 0.007764620240777731],
  [0, 0.0065854499116539955],
  [0, 0.00568766612559557],
  [0, 0.005261446349322796],
  [0, 0.005080060567706823],
  [0, 0.005363127216696739],
  [0, 0.005494296550750732],
  [0, 0.0052209533751010895],
  [0, 0.004440079443156719],
  [0, 0.0046133906580507755],
  [0, 0.004069915506988764],
  [0, 0.004061697516590357],
  [0, 0.0040739066898822784],
  [0, 0.004570570308715105],
  [0, 0.004002463072538376],
  [0, 0.0038893157616257668],
  [0, 0.004397805780172348],
  [0, 0.004198308568447828],
  [0, 0.004191816318780184],
  [0, 0.0038079447112977505],
  [0, 0.003797368612140417],
  [0, 0.003580823540687561],
  [0, 0.0034042843617498875],
  [0, 0.003616353962570429],
  [0, 0.003990973811596632],
  [0, 0.0035532598849385

In [3]:
import os
print(logger.experiment_dir)
metrics_file = os.path.join(logger.experiment_dir, 'metrics.json')

experiments/20240715-042250


In [5]:
with open(metrics_file, 'r') as f:
    print(f.read())

FileNotFoundError: [Errno 2] No such file or directory: 'experiments/20240715-042250/metrics.json'