In [10]:
import numpy as np
import pygame

# Initialize Pygame
pygame.init()
frame = np.load('rest.np.npy')
print("Frame shape:", frame.shape)
# Example frame of 0s and 1s
# frame = np.array([
#     [0, 1, 0, 1],
#     [1, 0, 1, 0],
#     [0, 1, 0, 1],
#     [1, 0, 1, 0]
# ])
print(frame[0])
# Set screen dimensions and scaling
width, height = frame.shape
scale = 10
screen_width, screen_height = width * scale, height * scale

# Create Pygame screen
screen = pygame.display.set_mode((screen_width, screen_height))

# Convert the frame to an RGB surface
frame_surface = (frame[:, :, np.newaxis] ).repeat(3, axis=2).astype(np.uint8)
print("Frame surface shape:", frame_surface.shape)
print("Frame surface data:\n", frame_surface)

# Make a Pygame surface from the array
surface = pygame.surfarray.make_surface(frame_surface)
print("Surface created:", surface)

# Scale the surface
scaled_surface = pygame.transform.scale(surface, (screen_width, screen_height))
print("Scaled surface created:", scaled_surface)

# Blit to the screen and update display
screen.blit(scaled_surface, (0, 0))
pygame.display.flip()

# Print the frame for debugging
print('\n'.join([''.join(['#' if pixel else '.' for pixel in row]) for row in frame]))

# Keep the window open for a short duration to view the output
pygame.time.wait(2000)

# Quit Pygame
pygame.quit()


Frame shape: (32, 64)
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0 255   0   0   0   0   0   0   0   0   0
   0 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]
Frame surface shape: (32, 64, 3)
Frame surface data:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Surface created: <Surface(32x64x32 SW)>
Scaled surface created: <Surface(320x640x32 SW)>
..........................#..........#..........................
..........................#..........#..........................
..........................#...